server:
  port: 8085
spring:
  application:

    name: chat
  main:
    allow-circular-references: true
  data:
    redis:
      port: 6379
      host: localhost
  rsocket:
    server:
      port: 6565
      transport: "tcp"
      mapping-path: "/rsocket"
  profiles:
    active: dev

# custom properties
custom:
  jwt:
    secret-key: ENC(+GbV3Ykx/t5XFlaFHBZnXTzsSf9b3YChS2cVPTvCgwQmevtbB1Hfw91VMC/fTizxVssJvYiAMeQICsuoSrH5zNLh/jxJsXq/)

logging:
  level:
    root: trace